version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
    container_name: postgres
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: redis
